### ISSUE TITLE
How to avoid timing attacks?

### ISSUE THREAD

**Issue by gethvi** [hynek/argon2-cffi#121]
Based on the example of login function from the docs:
```
import argon2


ph = argon2.PasswordHasher()


def login(db, user, password):
    hash = db.get_password_hash_for_user(user)

    # Verify password, raises exception if wrong.
    ph.verify(hash, password)

    # Now that we have the cleartext password,
    # check the hash's parameters and if outdated,
    # rehash the user's password in the database.
    if ph.check_needs_rehash(hash):
        db.set_password_hash_for_user(user, ph.hash(password))
```

If the user doesn't exist and therefore no hash is returned from the database, how would you suggest to avoid timing attack aiming to enumerate existing users?

Is having some bogus hash to verify a feasible approach?

Sorry if this doesn't belong here.

Thank you!

**Comment by hynek** [comment]
I don't think you can trick a truly dedicated attacker from this. Hashing bogus hash is expensive, so I'd rather measure the typical time and sleep for it with a random jitter to make it less predictable. But in the end the real answer is rate limiting.
