### ISSUE TITLE
Question: Can output from argon2.low_level.hash_secret_raw() → bytes directly used to derive aes key?

### ISSUE THREAD

**Issue by evil-user** [hynek/argon2-cffi#126]
Hi @hynek can output from argon2.low_level.hash_secret_raw(secret: [bytes](https://docs.python.org/3/library/stdtypes.html#bytes), salt: [bytes](https://docs.python.org/3/library/stdtypes.html#bytes), time_cost: [int](https://docs.python.org/3/library/functions.html#int), memory_cost: [int](https://docs.python.org/3/library/functions.html#int), parallelism: [int](https://docs.python.org/3/library/functions.html#int), hash_len: [int](https://docs.python.org/3/library/functions.html#int), type: [argon2.low_level.Type](https://argon2-cffi.readthedocs.io/en/stable/api.html#argon2.low_level.Type), version: [int](https://docs.python.org/3/library/functions.html#int) = 19) → [bytes](https://docs.python.org/3/library/stdtypes.html#bytes)[¶](https://argon2-cffi.readthedocs.io/en/stable/api.html#argon2.low_level.hash_secret) be used as cryptographic key?

**Comment by hynek** [comment]
I _think_ you'd want `hash_secret_raw` for that?

**Comment by evil-user** [comment]
@hynek  i want to use argon2 as key derivation function will hash_secret_raw be suitable for such use

**Comment by hynek** [comment]
Argon2 is a key-derivation library, but I'm not comfortable answering such a general question. I would take it to https://crypto.stackexchange.com or the Argon2 authors.
