### ISSUE TITLE
PyCharm is probably confused about src package_dir

### ISSUE THREAD

**Issue by piotr-szpetkowski** [hynek/argon2-cffi#46]
Hi.

I've a rather simple project based on setuptools for packaging and a few groups of dependencies (but that's probably not important). Now, I've decided to use this argon2 package for hashing in my app and everything works great, but I keep being nagged by PyCharm that:

> Package containing module argon2 is not listed in project requirements.

Which is obviously not true because I've just installed it with help of project requirements. My guess is that PyCharm does not understand `package_dir`. Now I know that it would be a problem which should be reported to PyCharm issues, however it would probably be much faster to resolve the problem with update to structure of this repo.

Thanks for this project and feel free to close this issue if you disagree.

**Comment by hynek** [comment]
That's highly unlikely because there are *a lot* of packages that use a src directory a nobody ever complained. Either PyCharm is confused or something else went wrong...
