### ISSUE TITLE
PasswordHasher is removed in 0.1.10, how to generate password?

### ISSUE THREAD

**Issue by jondkelley** [hynek/argon2-cffi#50]
New to this library but the docs don't seem to match the library anymore.

>>> from argon2 import PasswordHasher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PasswordHasher'
>>> import argon2
>>> dir(argon2)
['ARRAY', 'Argon2Exception', 'Argon2Type', 'ArgumentError', 'Array', 'BigEndianStructure', 'CDLL', 'CFUNCTYPE', 'DEFAULT_MODE', 'IS_PY2', 'LibraryLoader', 'LittleEndianStructure', 'POINTER', 'PYFUNCTYPE', 'PyDLL', 'RTLD_GLOBAL', 'RTLD_LOCAL', 'SetPointerType', 'Structure', 'Union', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__warningregistry__', '_argon2', '_crypto_argon2', '_ensure_bytes', 'addressof', 'alignment', 'argon2_hash', 'byref', 'c_bool', 'c_buffer', 'c_byte', 'c_char', 'c_char_p', 'c_double', 'c_float', 'c_int', 'c_int16', 'c_int32', 'c_int64', 'c_int8', 'c_long', 'c_longdouble', 'c_longlong', 'c_short', 'c_size_t', 'c_ssize_t', 'c_ubyte', 'c_uint', 'c_uint16', 'c_uint32', 'c_uint64', 'c_uint8', 'c_ulong', 'c_ulonglong', 'c_ushort', 'c_void_p', 'c_voidp', 'c_wchar', 'c_wchar_p', 'cast', 'cdll', 'create_string_buffer', 'create_unicode_buffer', 'get_errno', 'imp', 'memmove', 'memset', 'os', 'platform', 'pointer', 'py_object', 'pydll', 'pythonapi', 'resize', 'set_errno', 'sizeof', 'string_at', 'sys', 'system_type', 'wstring_at']
>>>

**Comment by hynek** [comment]
There is no 0.1.10. Did you accidentally install argon2 instead of argon2-cffi?
