### ISSUE TITLE
Move wheel builder from pyca/infra into this repo

### ISSUE THREAD

**Issue by alex** [hynek/argon2-cffi#51]
https://github.com/pyca/infra/blob/master/external-projects/argon2cffi-wheel-builder.yml

should just be a matter of copying it from there to here and you configuring your azure pipelines account

**Comment by hynek** [comment]
Would this become part of CI? I'll be moving argon2-cffi to AP anyways. Would the mentioned file be something extra? Should I integrate it? 🤔

**Comment by alex** [comment]
For bcrypt/cryptography/etc. we don't run these on all builds, we manually trigger them as necessary.

For those we put this at `.azure-pipelines/wheel-builder.yml` and configured a second pipeline.

**Comment by hynek** [comment]
I have conquered it, thank you!
