### ISSUE TITLE
Threading failure causes application to crash

### ISSUE THREAD

**Issue by ChrisTerBeke** [hynek/argon2-cffi#53]
We're seeing the following error being raised if we catch all exceptions:

```
argon2.exceptions.HashingError: Threading failure"
```

In some cases is also brings down the entire application without logging anything.

**Comment by hynek** [comment]
This error is coming directly from Argon2 the C library. Is it possible, that you're running in an environment that restricts threading in any way? Try setting `parallelism=1` and see if it helps.

**Comment by ChrisTerBeke** [comment]
We're running in a Docker + Kubernetes environment, shouldn't be a problem. But I'll try parallelism=1 and let you know. Thanks!

**Comment by hynek** [comment]
Double check your memory usage too.

**Comment by ChrisTerBeke** [comment]
It seems memory usage is increasing over time, eventually causing the container to run out of memory and Kubernetes killing it. Could this be related to this package? We see a lot of FUTEX access in Linux (which is used by Python threading).

**Comment by hynek** [comment]
This package contains no threading code whatsoever, so that's unlikely. Of course I can't rule rule out memory leaks, but I'm not aware of any and I'd expect to hear at least from from pypi/warehouse if there were any.

**Comment by ChrisTerBeke** [comment]
For now we have increased our memory limits and added extra logging to gather more information. Will let you know if we find anything. Thanks!
