### ISSUE TITLE
How to implement a progress bar

### ISSUE THREAD

**Issue by mbarkhau** [hynek/argon2-cffi#54]
My use case involves relatively expensive hashing using argon2. Expensive enough to warrant a progress bar. Is there any way I could hook up a callback so that the progress bar would be meaningful?

If this is not possible, what would the security risk be, if I did repeated hashing outside of the argon2 module, for example like this:

```python
# pseudocode
def argon_with_progress(in_data, progress_callback, time_cost=1000):
    current_hash_value = in_data
    for i in range(100):
        current_hash_value = argon2hash(hash_value, time_cost=time_cost // 100)
        progress_callback(i / 100.0)
    return current_hash_value
```

**Comment by hynek** [comment]
I don't think the argon2 implementation offers anything like that. If you know roughly how long it takes, you could probably do a progress bar based entirely on time|

**Comment by mbarkhau** [comment]
Ok, thanks for the feedback.
