### ISSUE TITLE
How to verify secret for low_level not clear

### ISSUE THREAD

**Issue by aaronbuchwald** [hynek/argon2-cffi#55]
How do you use the verify secret function for a hash generated by argon2.low_level.hash_secret_raw. This function returns only bytes, but it is not the full hash used with the low level verify secret function. How should the hash produced by hash_secret_raw be verified along with the salt used to create it?

**Comment by hynek** [comment]
Well, if you have all the parameters (including salt), you can hash another secret and compare the resulting hashes (e.g. using `secrets.compare_digest()` from the stdlib). It's usually not a great idea to use those low-level functions though.
