### ISSUE TITLE
Type Hints (PEP 484)

### ISSUE THREAD

**Issue by retnikt** [hynek/argon2-cffi#60]
Could inline type hints be added to Argon2 for mypy and other introspection compatibility? Since Python 3.5+ is required anyway there would be no backwards-incompatibility issues, or at least PEP 561 Stub files. I would be willing to work on a PR if you want.

See https://www.python.org/dev/peps/pep-0561/ and https://www.python.org/dev/peps/pep-0484/

**Comment by hynek** [comment]
3.5+ but also 2.7. :| I've already dropped 2.7 support on some of my projects, but I'm somewhat uneasy to do it also for such a security-sensitive one.  There's prob quite a few of Django installations depending on it…

I guess we could add it using `pyi` files but man that's tiring. :(

**Comment by piotr-szpetkowski** [comment]
@hynek 
If you are not willing to drop 2.7 yet there are few possible solutions that come to mind:
1. 3.5+ only on master and a separate `20.1.x` branch for backport security fixes (seems to me like less of a hassle than `pyi` files which would eventually mean double of the effort)
2. Fork into something like `argon2-cffi-typed` and merge with `argon2-cffi` when ready to abandon 2.7.

I already have some typing stubs defined in a private project e.g. for `PasswordHasher` and would gladly provide a PR if you would accept it.

**Comment by hynek** [comment]
I mean we could hold our noses and stubs for now? The APIs are rather simple, so it should be straight-forward?

**Comment by piotr-szpetkowski** [comment]
Stubs are working fine for me atm (as mentioned in previous post, I already have them defined in a private project) -- I just decided to throw some ideas in case if you'd be looking for a way to introduce typing annotations here in upstream.

**Comment by rob4226** [comment]
Hi @pszpetkowski would you mind sharing those stubs?  I'd like to clear the mypy errors from my project. Thanks!

**Comment by hynek** [comment]
We have dropped 2.7 and 3.5 a while ago, so I'd be happy to accept proper stubs here!

**Comment by hynek** [comment]
They will after the next release. I've pompously shipped type hints but forgot to add a `py.typed` marked. Therefore, currently MyPy won't find the stubs. 🤦🏻‍♂️ 

I will release later this week. I'm just waiting if more problems pop up.
