### ISSUE TITLE
ModuleNotFoundError: No module named 'argon2'

### ISSUE THREAD

**Issue by alexandreraufast** [hynek/argon2-cffi#63]
I installed with `pip3 install argon2-cffi` but when running `from argon2 import PasswordHasher`, python returns `ModuleNotFoundError: No module named 'argon2'`
I use Python 3.8.1 with anaconda

Any idea about what I'm doing wrong ?

**Comment by alexandreraufast** [comment]
Ok, I figured out that I should use `pip install argon2-cffi` and not `pip3`. My mistake.

**Comment by hynek** [comment]
I would even recommend to use [`python -m pip`](https://snarky.ca/why-you-should-use-python-m-pip/) to void such problems in the future.
