### ISSUE TITLE
would a python-3.9 wheel be possible ?

### ISSUE THREAD

**Issue by stonebig** [hynek/argon2-cffi#66]

**Comment by hynek** [comment]
Unfortunately our wheel builder is broken again and I'll have to invest hours to get it back into a working state.

**Comment by hynek** [comment]
Hail Mary: @asottile any chance you have something we could copy paste? My wheel build infra is completely busted and you seemed to be more in it?

**Comment by asottile** [comment]
sure I can take a look!

**Comment by asottile** [comment]
given the stuff I set up before, we should only need to build cp39 wheels for windows the cp35-abi3 wheels will work for linux and the cp37-abi3 wheels will work for macos

**Comment by asottile** [comment]
ah ok I went to look into this more, looks like the way mine works uses a feature that's not implemented for github actions (only for azure pipelines :sob:) -- https://github.com/asottile/azure-pipeline-templates/blob/c05f40d916aa33ae8dab84461c1872dc4e2838ab/job--python-tox.yml#L88-L103

I really only use it for windows / macos

@hynek what were you using before and I can see what I can do for it

**Comment by hynek** [comment]
You contributed to it which is why I pinged you! 😅 (I usually wouldn’t pull people into my problems)

I used to use AP too, the YAML is still there, but the base container got nuked and I suspect there’s a better way to do it nowadays?

**Comment by asottile** [comment]
so the cool thing is we're already set on macos / linux (this was the work that I did before):

```
$ virtualenv venv -ppython3.9
. ve	created virtual environment CPython3.9.0.final.0-64 in 739ms
  creator CPython3Posix(dest=/tmp/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv)
    added seed packages: pip==20.2.3, setuptools==50.3.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ . venv/bin/activate
(venv) $ pip install argon2-cffi
Collecting argon2-cffi
  Using cached argon2_cffi-20.1.0-cp35-abi3-manylinux1_x86_64.whl (97 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cffi>=1.0.0
  Downloading cffi-1.14.3-cp39-cp39-manylinux1_x86_64.whl (405 kB)
     |████████████████████████████████| 405 kB 398 kB/s 
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: six, pycparser, cffi, argon2-cffi
Successfully installed argon2-cffi-20.1.0 cffi-1.14.3 pycparser-2.20 six-1.15.0
```

the only platform that doesn't yet support abi3 is windows (I'm praying it comes soon) -- so all we need to do is get the windows build working and producing an artifact somehow

**Comment by hynek** [comment]
Well it’s only so-so cool. 😐

Yes, the windows wheel is urgent (argon2-cffi is used by Jupyter and I’ve already received an _e-mail_ about it #todayInOpenSource) but it would be amazeballs if we (sorry again 😅) could end up with a working wheel builder for argon2-cffi so I don’t have to dread the next release. 😅

But yeah, just a windows wheel would take off the heat a lot.

**Comment by asottile** [comment]
I'll see what I can do when I'm back at home tomorrow 👍 (on vacation at the moment and I'm being told to go to bed now I shouldn't be on the computer!)

**Comment by hynek** [comment]
Omg enjoy your vacation!

**Comment by SmartManoj** [comment]
https://t.me/Python4Channel/154

**Comment by asottile** [comment]
so good news, it looks like abi3 kinda just works on windows now? I'm not quite sure what changed but I just tried it for one of my packages and everything seems great?

I'll apply the same patch here and see what I can do to get deployments more automated

**Comment by hynek** [comment]
Thanks to @asottile, there are 3.9 Windows wheels on PyPI now.
