### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [hynek/argon2-cffi#73]
**Summary**
Installing argon2-cffi on aarch64 via pip using command "pip3 install argon2-cffi" tries to build wheel from source code

**Problem description**
argon2-cffi doesn't have wheel for aarch64 on PyPI repository. So, while installing argon2-cffi via pip on aarch64, pip builds wheel for same resulting in it takes more time to install argon2-cffi. Making wheel available for aarch64 will benefit aarch64 users by minimizing argon2-cffi installation time.

**Expected Output**
Pip should be able to download argon2-cffi wheel from PyPI repository rather than building it from source code.

@argon2-cffi-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make argon2-cffi wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by hynek** [comment]
Are there any CIs available that provide AArch64 VMs?  There's also https://www.piwheels.org/project/argon2-cffi/ could theirs wheels be somehow reused or something?

**Comment by MuhammadAsadJaved** [comment]
@odidev  Are you able to install it on aarch64? I am trying to install on Xavier NX and go the following errors. 
I have tried with `pip install argon2-cffi`  and `pip3 install argon2-cffi`
![Screenshot from 2020-11-26 16-52-30](https://user-images.githubusercontent.com/28862708/100328719-cdc3d600-3007-11eb-9b62-e2c09c9e5ea8.png)

**Comment by odidev** [comment]
@MuhammadAsadJaved I am not hitting this issue on aarch64. Please see below logs-

>[root@2cd238138ca8 /]# find / -name "ffi.h"
[root@2cd238138ca8 /]# uname -m
aarch64
[root@2cd238138ca8 /]# pip3 install argon2-cffi --no-cache-dir
Collecting argon2-cffi
  Downloading argon2-cffi-20.1.0.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 2.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cffi>=1.0.0 in /opt/_internal/cpython-3.8.5/lib/python3.8/site-packages (from argon2-cffi) (1.14.4)
Requirement already satisfied: six in /opt/_internal/cpython-3.8.5/lib/python3.8/site-packages (from argon2-cffi) (1.15.0)
Requirement already satisfied: pycparser in /opt/_internal/cpython-3.8.5/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi) (2.20)
Building wheels for collected packages: argon2-cffi
  Building wheel for argon2-cffi (PEP 517) ... done
  Created wheel for argon2-cffi: filename=argon2_cffi-20.1.0-cp38-abi3-linux_aarch64.whl size=96651 sha256=0b1fc9ef904a0b5df2c493b5f060040f5446e089f6393a58740eb8022d8696c6
  Stored in directory: /tmp/pip-ephem-wheel-cache-dpwe8g8t/wheels/a8/61/59/3fb44bae5cfd2c3d86682f7778670cb0800f7da9bd98450d70
Successfully built argon2-cffi
Installing collected packages: argon2-cffi
Successfully installed argon2-cffi-20.1.0
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the '/opt/_internal/cpython-3.8.5/bin/python3.8 -m pip install --upgrade pip' command.
[root@2cd238138ca8 /]#

**Comment by hynek** [comment]
This is fixed by the outsourcing to https://github.com/hynek/argon2-cffi-bindings 

Feel free to try to pip-install argon2-cffi-bindings and report back if it's still broken.
