### ISSUE TITLE
Unable to install on Xavier NX

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [hynek/argon2-cffi#77]
Hi, I am trying to install on Nvidia Xavier NX but there is an error.
I have tried with `pip install argon2-cffi`  and `pip3 install argon2-cffi`

Here is the error message. 
![Screenshot from 2020-11-26 16-52-30](https://user-images.githubusercontent.com/28862708/100329061-285d3200-3008-11eb-8b45-b295d8deb359.png)

**Comment by hynek** [comment]
I don't know what distro Xavier NX is running (hearing about it for the first time), but you need to install libffi development files. If it's a debian descendant, it's called `libffi-dev` on RedHat flavors it should be `libffi-devel`.
